### ISSUE TITLE
Retrieve users from db and serve to authorized requests (60 mins)

### ISSUE THREAD

**Issue by marcoantonioghiani01** [vlab-research/dashboard-server#2]
Connect to the database and retrieve the user's information.
Follow RESTful API standard.
Tasks:
- Connect database and generate pool
- GET /users =>  serve all users information

Nice to have:
- GET /users/:id => serve specific user information

**Comment by nandanrao** [comment]
Not really interested in getting any info on the "user" (respondent) level right now!

**Comment by nandanrao** [comment]
(however, we can change that to accepting a "formid" parameter, which would be nice to have!)
